export default {
  login: "Ajayjha911",
  id: 53463368,
  node_id: "MDQ6VXNlcjUzNDYzMzY4",
  avatar_url: "https://avatars3.githubusercontent.com/u/53463368?v=4",
  gravatar_id: "",
  url: "https://api.github.com/users/Ajayjha911",
  html_url: "https://github.com/Ajayjha911",
  followers_url: "https://api.github.com/users/Ajayjha911/followers",
  following_url:
    "https://api.github.com/users/Ajayjha911/following{/other_user}",
  gists_url: "https://api.github.com/users/Ajayjha911/gists{/gist_id}",
  starred_url: "https://api.github.com/users/Ajayjha911/starred{/owner}{/repo}",
  subscriptions_url: "https://api.github.com/users/Ajayjha911/subscriptions",
  organizations_url: "https://api.github.com/users/Ajayjha911/orgs",
  repos_url: "https://api.github.com/users/Ajayjha911/repos",
  events_url: "https://api.github.com/users/Ajayjha911/events{/privacy}",
  received_events_url:
    "https://api.github.com/users/Ajayjha911/received_events",
  type: "User",
  site_admin: false,
  name: null,
  company: null,
  blog: "http://mybloggingdjangoapp.herokuapp.com/",
  location: "New Delhi",
  email: null,
  hireable: null,
  bio: null,
  twitter_username: null,
  public_repos: 8,
  public_gists: 0,
  followers: 0,
  following: 0,
  created_at: "2019-07-30T05:59:35Z",
  updated_at: "2021-01-08T07:43:58Z",
};
